pipeline:
  build:
    image: docker:git
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker buildx build -t app:local .

  deploy:
    image: docker:dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker run -ti -d app:local

